Repository Azure/aml-compute, pull requests merged in 2020-05, with the labels that each got.

#5 Add input validation and unit tests
  .cloud/.azure/aml_compute.json
  .github/workflows/python.yml
  .gitignore
  Dockerfile
  README.md
  code/main.py
  code/schemas.py
  code/utils.py
  tests/test_main.py
  tests/test_utils.py
Labels: enhancement

#7 Ashishonce/integration test
  .cloud/.azure/test/test_aks_compute.json
  .cloud/.azure/test/test_aml_compute.json
  .cloud/.azure/test/test_workspace.json
  .github/workflows/integration.yml
Labels: enhancement

#10 Change Cluster SKU Standard
  .cloud/.azure/aks_compute.json
  .cloud/.azure/aml_compute.json
  .cloud/.azure/test/test_aks_compute.json
  .cloud/.azure/test/test_aml_compute.json
  .cloud/.azure/test/test_workspace.json
  README.md
  code/utils.py
Labels: enhancement

#12 Updating README.md in alignment with other actions
  README.md
Labels: documentation

#13 Update azureml-sdk to 1.5.0
  Dockerfile
Labels: enhancement

#14 remove ls
  .gitattributes
  CODE_OF_CONDUCT.md
  LICENSE
  README.md
  SECURITY.md
  code/entrypoint.sh
Labels: bug

#15 Upgrade to Azure ML SDK 1.6.0
  Dockerfile
Labels: enhancement
